name: Run Symfony Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: app
          POSTGRES_PASSWORD: "!ChangeMe!"
          POSTGRES_USER: app
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          extensions: pdo_pgsql
          tools: composer, symfony

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Copy .env file
        run: cp .env.test .env

      - name: Start Docker containers
        run: docker-compose up -d

      - name: Run tests
        run: symfony php bin/phpunit

      - name: Stop Docker containers
        run: docker-compose down
